export const projects = [
  {
    img: '/projects/viptechstore.webp',
    name: 'Vip Tech Store',
    code: 'https://github.com/fernandohiroshi/viptech-store',
    live: 'https://www.viptech.store/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/konbinicode0.2.webp',
    name: 'Konbini Code 0.2',
    code: 'https://github.com/fernandohiroshi/KC-V2',
    live: 'https://konbinicode.com/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/autoway.webp',
    name: 'Autoway Marketplace',
    code: 'https://github.com/fernandohiroshi/autoway-marketplace',
    live: 'https://autoway-marketplace.vercel.app/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/planc.webp',
    name: 'PlanC',
    code: 'https://github.com/fernandohiroshi/micro-saas-app',
    live: 'https://planc-saas.vercel.app/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/kc01.webp',
    name: 'Konbini Code',
    code: 'https://github.com/fernandohiroshi/konbini-code',
    live: 'https://konbinicodev1.vercel.app/en',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/portfolio.webp',
    name: 'My Portfolio',
    code: 'https://github.com/fernandohiroshi/portfolio',
    live: 'https://fernandohiroshi.com/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/caroline.webp',
    name: 'Caroline Portfolio',
    code: 'https://github.com/fernandohiroshi/carolinesouza',
    live: 'https://www.carolinesouza.art/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/restaurante.webp',
    name: 'Restaurante',
    code: '',
    live: 'https://konbinicode-restaurante-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/pousada.webp',
    name: 'Pousada',
    code: '',
    live: 'https://konbinicode-pousada-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/tattoo.webp',
    name: 'Tattoo',
    code: '',
    live: 'https://konbinicode-tattoo-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/academia.webp',
    name: 'Academia',
    code: '',
    live: 'https://konbinicode-academia-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/petshop.webp',
    name: 'Petshop',
    code: '',
    live: 'https://konbinicode-petshop-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },

  {
    img: '/projects/beleza.webp',
    name: 'Beleza',
    code: '',
    live: 'https://konbinicode-beleza-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/lavacar.webp',
    name: 'Lavacar',
    code: '',
    live: 'https://konbinicode-lavacar-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/psicologa.webp',
    name: 'Psicóloga',
    code: '',
    live: 'https://konbinicode-psicologa-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/nutricao.webp',
    name: 'Nutrição',
    code: '',
    live: 'https://konbinicode-nutricao-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/lanchonete.webp',
    name: 'Lanchonete',
    code: '',
    live: 'https://konbinicode-lanchonete-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/jornalismo.webp',
    name: 'Jornalismo',
    code: '',
    live: 'https://konbinicode-jornalismo-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/barbearia.webp',
    name: 'Barbearia',
    code: '',
    live: 'https://konbinicode-barbearia-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: '/projects/evento.webp',
    name: 'Evento',
    code: '',
    live: 'https://konbinicode-evento-demo.vercel.app/',
    codeBtn: false,
    liveBtn: true,
  },
]
