export const projects = [
  {
    img: '/projects/viptechstore.webp',
    name: 'Vip Tech Store',
    code: 'https://github.com/fernandohiroshi/viptech-store',
    live: 'https://www.viptech.store/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/konbinicode0.2.webp',
    name: 'Konbini Code 0.2',
    code: 'https://github.com/fernandohiroshi/KC-V2',
    live: 'https://konbinicode.com/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/nestjs.webp',
    name: 'NestJS CRUD',
    code: 'https://github.com/fernandohiroshi/nestjs-crud',
    live: '',
    codeBtn: true,
    liveBtn: false,
  },
  {
    img: '/projects/planc.webp',
    name: 'PlanC',
    code: 'https://github.com/fernandohiroshi/micro-saas-app',
    live: 'https://planc-saas.vercel.app/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/caroline.webp',
    name: 'Caroline Portfolio',
    code: 'https://github.com/fernandohiroshi/carolinesouza',
    live: 'https://www.carolinesouza.art/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: '/projects/autoway.webp',
    name: 'Autoway Marketplace',
    code: 'https://github.com/fernandohiroshi/autoway-marketplace',
    live: 'https://autoway-marketplace.vercel.app/',
    codeBtn: true,
    liveBtn: true,
  },
]
