export const projects = [
  {
    img: 'https://imgix.cosmicjs.com/b1e6b4b0-80fe-11ef-9257-112b43bd2f70-Macbook-Air-konbinicode.com.png',
    name: 'Konbini Code',
    code: 'https://github.com/fernandohiroshi/konbini-code',
    live: 'https://konbinicode.com/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: 'https://imgix.cosmicjs.com/c07f4730-80fe-11ef-9257-112b43bd2f70-Macbook-Air-fernandohiroshi.com.png',
    name: 'My Portfolio',
    code: 'https://github.com/fernandohiroshi/portfolio',
    live: 'https://fernandohiroshi.com/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: 'https://imgix.cosmicjs.com/bf248fc0-ead6-11ef-af71-9552422268b6-dr-hair-profile.png',
    name: 'dr hair clinic',
    code: '',
    live: 'https://drhairtransplantecapilar.com.br/',
    codeBtn: false,
    liveBtn: true,
  },
  {
    img: 'https://imgix.cosmicjs.com/97b5d5e0-ae39-11ef-8a63-eb57d6c77a36-profilesite.png',
    name: 'carolinesouza.art',
    code: 'https://github.com/fernandohiroshi/carolinesouza',
    live: 'https://www.carolinesouza.art/',
    codeBtn: true,
    liveBtn: true,
  },
  {
    img: 'https://imgix.cosmicjs.com/a7fc4020-b202-11ef-8a63-eb57d6c77a36-top-bebidas.png',
    name: 'topbebidas.com',
    code: '',
    live: 'https://topbebidas.com/',
    codeBtn: false,
    liveBtn: true,
  },
]
